sudo: false
language: php
dist: trusty

php:
- 7.0
- 7.1
- 7.2
- nightly

jobs:
  include:
    - stage: check
      script: vendor/bin/phpcs
    - stage: test
      script:
      - vendor/bin/phpunit
    - stage: deploy
      script: skip
      deploy:
        provider: releases
        api_key: "GITHUB OAUTH TOKEN"
        file: "FILE TO UPLOAD"
        skip_cleanup: true
        on:
          tags: true

stages:
  - check
  - test
  - name: deploy
    if: branch = master

before_install:
  - composer self-update
  - composer require squizlabs/php_codesniffer ^3.0.0
  - composer require phpunit/phpunit ^6.0.0
