sudo: false
language: php
dist: trusty

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly

  allow_failures:
    - php: nightly

jobs:
  include:
    - stage: lint
      script: php -l
    - stage: check
      script: phpcs
    - stage: test
      script:
      - phpunit
    - stage: deploy
      script: skip
      deploy:
        provider: releases
        api_key: "GITHUB OAUTH TOKEN"
        file: "FILE TO UPLOAD"
        skip_cleanup: true
        on:
          tags: true

stages:
  - lint
  - check
  - test
  - name: deploy
    if: branch = master

before_install:
  - composer self-update
  - composer require squizlabs/php_codesniffer ^3.0.0
  - composer require phpunit/phpunit ^6.0.0
